name: Build and Release on Tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Web Dependencies
        run: npm ci

      - name: Build Web
        run: npm run build

      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: apps/web/build

  build-streamdeck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: plugins/stream-deck-plushie-bridge
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Plugin Dependencies
        run: npm ci

      - name: Build Plugin (optional)
        run: npm run build

      - name: Show working dir contents (debug)
        run: ls -R .

      - name: Package StreamDeck Plugin
        uses: neilenns/streamdeck-cli-pack@v1
        with:
          path: plugins/stream-deck-plushie-bridge/com.olfusitus.stream-deck-plushie-bridge.sdPlugin

      - name: Upload StreamDeck Plugin
        uses: actions/upload-artifact@v4
        with:
          name: streamdeck-plugin
          path: plugins/stream-deck-plushie-bridge/*.streamDeckPlugin

  publish-tauri:
    needs: [build-web, build-streamdeck]
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        working-directory: apps/desktop
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Install Frontend Dependencies
        run: npm ci

      - name: Install Web Dependencies
        working-directory: apps/web
        run: npm ci

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: apps/desktop
          tagName: plushie-v__VERSION__
          releaseName: "Plushie v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}

  attach-other-assets:
    name: "Attach Web & Plugin"
    needs: [publish-tauri]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: "*"
          path: artifacts

      - name: Upload extra assets to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: plushie-v${{ github.run_number }}
          files: |
            artifacts/web-build/**
            artifacts/streamdeck-plugin/*.streamDeckPlugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
